package io.github.naveenkumar.jmeter.superkey.pro;

import org.apache.jmeter.util.JMeterUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.nio.charset.StandardCharsets;
import java.security.KeyFactory;
import java.security.PublicKey;
import java.security.Signature;
import java.security.spec.X509EncodedKeySpec;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Base64;

/**
 * LicenseManager — offline RSA signature verification for SuperKey Pro.
 *
 * <p>
 * Expects a {@code superkey.lic} file in the JMeter home directory containing
 * a developer-signed payload using SHA256withRSA.
 *
 * <p>
 * <b>NOTE:</b> This class is intentionally kept in the {@code pro} package.
 * The OSS Maven build profile excludes the entire {@code pro/**} package from
 * compilation.
 */
public final class LicenseManager {

    private static final Logger log = LoggerFactory.getLogger(LicenseManager.class);

    /** Name of the license file expected in {@code $JMETER_HOME}. */
    private static final String LICENSE_FILE_NAME = "superkey.lic";

    /** Hardcoded Public Key generated by RSAKeyGenerator (2048-bit). */
    private static final String PUBLIC_KEY_BASE64 = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7yrqmVP5KzD1hG7ib2XHW4qFSAkyvnkTj2Lptx0EP6Ya+DA0o+i7QrXL4awQWnYl3O7v4iU8Ca0v18wZLQJmNthKgdlsH3OTxVCA2wK+iRH/4DiXXEeps29Ky0id4NEWTmJeiMpt7Z9VGysB5+rOj6P2RC9PJH83W5TLmLpxMpAkxV4LlhYH2cFE3G37yvrdtBCY6fJkJIHR83HEkprypoM60qJ7oxlf9AlPv/+CTdW34hOasJpYMnFCiBpeZd8ZYwWfj9QLI/6DuYGnbc3OcrDzh6/Xl4i8GM7rSOowWTWia0hw4zTsqlecPuXn7VaZJUabo3LwPHg8jGdop5JH9wIDAQAB";
    // Note: Used the public key generated earlier (joined lines).

    private static Boolean cachedResult = null;
    private static String cachedEmail = null;
    private static String cachedExpiry = null;

    private LicenseManager() {
        /* utility class */ }

    /**
     * Returns {@code true} when a cryptographically valid Pro license is detected.
     */
    public static synchronized boolean isPro() {
        if (cachedResult != null) {
            return cachedResult;
        }
        cachedResult = detect();
        return cachedResult;
    }

    public static String getLicensedEmail() {
        isPro(); // trigger detection
        return cachedEmail;
    }

    public static String getLicenseExpiry() {
        isPro(); // trigger detection
        return cachedExpiry;
    }

    private static boolean detect() {
        try {
            String home = JMeterUtils.getJMeterHome();
            if (home == null) {
                // Fallback to current directory for local testing
                home = System.getProperty("user.dir");
            }
            File licFile = new File(home, LICENSE_FILE_NAME);
            if (licFile.exists() && licFile.isFile()) {
                return validateLicenseFile(licFile);
            }
        } catch (Exception e) {
            log.debug("Could not locate JMeter home during license check", e);
        }

        log.info("SuperKey Pro: no valid license found ('superkey.lic' missing) — running in OSS mode.");
        return false;
    }

    private static boolean validateLicenseFile(File licFile) {
        String name = null;
        String email = null;
        String tier = null;
        String expires = null;
        String signatureBase64 = null;

        try (BufferedReader br = new BufferedReader(new FileReader(licFile))) {
            String line;
            while ((line = br.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("Name: "))
                    name = line.substring(6).trim();
                else if (line.startsWith("Email: "))
                    email = line.substring(7).trim();
                else if (line.startsWith("Tier: "))
                    tier = line.substring(6).trim();
                else if (line.startsWith("Expires: "))
                    expires = line.substring(9).trim();
                else if (line.startsWith("Signature: "))
                    signatureBase64 = line.substring(11).trim();
            }
        } catch (Exception e) {
            log.warn("SuperKey Pro: Failed to read license file '{}'", licFile.getAbsolutePath(), e);
            return false;
        }

        if (name == null || email == null || tier == null || expires == null || signatureBase64 == null) {
            log.warn("SuperKey Pro: License file is missing required fields.");
            return false;
        }

        // Reconstruct the exact payload the generator signed
        String payload = String.format("Name=%s\nEmail=%s\nTier=%s\nExpires=%s", name, email, tier, expires);

        try {
            boolean isSignatureValid = verifySignature(payload, signatureBase64, PUBLIC_KEY_BASE64);
            if (!isSignatureValid) {
                log.warn("SuperKey Pro: RSA Signature verification FAILED! The license is forged or corrupted.");
                return false;
            }
        } catch (Exception e) {
            log.warn("SuperKey Pro: Cryptographic error while verifying license.", e);
            return false;
        }

        // Check expiry date
        if (!"never".equalsIgnoreCase(expires)) {
            try {
                LocalDate expiryDate = LocalDate.parse(expires, DateTimeFormatter.ISO_LOCAL_DATE);
                if (LocalDate.now().isAfter(expiryDate)) {
                    log.warn("SuperKey Pro: SSLicense expired on {}.", expires);
                    return false;
                }
            } catch (Exception e) {
                log.warn("SuperKey Pro: Invalid expiry date format '{}'.", expires);
                return false;
            }
        }

        cachedEmail = email;
        cachedExpiry = expires;
        log.info("SuperKey Pro License Verified \u2713 | Licensed to: {} | Expiry: {}", email, expires);
        return true;
    }

    private static boolean verifySignature(String payload, String signatureBase64, String publicKeyBase64)
            throws Exception {
        byte[] keyBytes = Base64.getDecoder().decode(publicKeyBase64);
        X509EncodedKeySpec spec = new X509EncodedKeySpec(keyBytes);
        KeyFactory kf = KeyFactory.getInstance("RSA");
        PublicKey publicKey = kf.generatePublic(spec);

        Signature signature = Signature.getInstance("SHA256withRSA");
        signature.initVerify(publicKey);
        signature.update(payload.getBytes(StandardCharsets.UTF_8));

        byte[] sigBytes = Base64.getDecoder().decode(signatureBase64);
        return signature.verify(sigBytes);
    }
}
